version: 2

sphinx:
  configuration: docs/conf.py
  fail_on_warning: false
  builder: html

build:
  image: latest
  apt_packages:
    - imagemagick

python:
  version: 3.8
  system_packages: true
  install:

    - requirements: rtd-requirements.txt

    - requirements: requirements.txt

    - method: setuptools
      path: .
    
    - method: pip
      path: .
      extra_requirements:
        - docs
        - src
    
