version: 2
mkdocs: {}
build:
  image: "7.0"
  apt_packages:
    - imagemagick

python:
  version: 3.8
  system_packages: true
  install:

    - requirements: rtd-requirements.txt

    - requirements: requirements.txt
