version: 2

sphinx:
  configuration: docs/conf.py
  fail_on_warning: false
  builder: html

build:
  image: 8.0
  python: 3.9
  system_packages:
    - imagemagick
  extras:
    - rust==1.52.0

python:
  version: 3.8
  system_packages: true
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
        - src

    - requirements: rtd-requirements.txt

    - requirements: requirements.txt

    - method: setuptools
      path: .
